name: Typescript Project `Blog-app` CI With Docker
on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
            context: .
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/blogapp:latest
      -
        name: Run the docker container
        run: |
            sudo docker stop blogapp || true
            sudo docker rm blogapp || true
            sudo docker image rm ${{ secrets.DOCKERHUB_USERNAME }}/blogapp:latest || true
            sudo docker run --name blogapp -d -p 8000:8000 \
              -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
              -e PORT=${{ secrets.PORT }} \
              -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
              -e FILEPATH=${{ secrets.FILEPATH }} \
              ${{ secrets.DOCKERHUB_USERNAME }}/blogapp:latest       